"""Compatibility wrapper for legacy import path: BluePanda/Nodos/Tags.py"""
from ..nodes.decorators.tags import (
    component,
    CharacterBody2D,
    CollisionShape2D,
    Sprite2D,
    TimerNode,
    Area2D,
    ButtonNode,
    Label,
    PanelNode,
    AnimatedSprite,
    ScriptNode,
    PhysicsBody2D,
    HealthNode,
    PatrolNode2D,
    ParticleEmitterNode2D,
    StateMachineNode,
    OnReady,
    OnEvent,
    OnSignal,
)
